name: Waka Readme
on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every night at midnight UTC
  workflow_dispatch: # Allows you to run it manually right now!
jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
